version: "3"
services:
  db:
    image: mysql:5.7
    container_name: golang-crud-sample_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: golang_crud_sample_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/my.cnf:/etc/mysql/my.cnf
  app:
    build: .
    container_name: golang-crud-sample_app
    command: go run main.go
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app